[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["Zach Rayburn <zcrhome@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rust-crypto = "0.2.36"
base64 = "0.10.1"
rustc-serialize = "0.3.24"
